# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

dependencies:
  pre:
    - gem update fastlane

jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout
      - run: bundle exec fastlane test